
// CONTENIDO: cambia nombres, textos y lugares en el HTML.
// DISEÑO: cambia colores y tipografías en el bloque CSS de arriba.
// INTERACCIÓN: JavaScript controla apertura, reloj, música y confirmación.
const EVENT_DATE='2027-08-14T18:00:00-06:00';
const $=id=>document.getElementById(id);
$('open').addEventListener('click',()=>{$('cover').classList.add('opened');$('inicio').classList.add('reveal');$('sound').focus({preventScroll:true});});
function tick(){let remaining=Math.max(0,new Date(EVENT_DATE)-Date.now());$('days').textContent=Math.floor(remaining/86400000);$('hours').textContent=String(Math.floor(remaining/3600000)%24).padStart(2,'0');$('minutes').textContent=String(Math.floor(remaining/60000)%60).padStart(2,'0');$('seconds').textContent=String(Math.floor(remaining/1000)%60).padStart(2,'0');if(!remaining)$('countnote').textContent='¡Llegó el gran día!';}tick();setInterval(tick,1000);
function download(text,type,name){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('calendar').addEventListener('click',()=>download(['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//ONCE9//Wedding Demo//ES','BEGIN:VEVENT','UID:valentina-xv-demo-20270815@once9.example','DTSTAMP:20261006T080000Z','DTSTART:20270815T000000Z','DTEND:20270815T060000Z','SUMMARY:XV de Valentina (demo)','LOCATION:Ciudad de México — ubicación de ejemplo','DESCRIPTION:Evento ilustrativo de la demo ONCE9.','END:VEVENT','END:VCALENDAR'].join('\r\n'),'text/calendar;charset=utf-8','xv-valentina-demo.ics'));
const KEY='once9-xv-demo-rsvp';function display(response){$('result').hidden=false;$('result').textContent=response.attendance==='yes'?`¡Gracias, ${response.name}! Respuesta de prueba: asistirás con un total de ${response.count} persona(s).`:`Gracias, ${response.name}. Tu respuesta de prueba indica que no podrás asistir.`;$('reset').hidden=false;}
$('attendance').addEventListener('change',()=>{$('count').disabled=$('attendance').value==='no';});
$('rsvpForm').addEventListener('submit',event=>{event.preventDefault();const name=$('guest').value.trim();if(!name){$('guest').setCustomValidity('Escribe tu nombre.');$('guest').reportValidity();return;}const response={name,attendance:$('attendance').value,count:$('attendance').value==='yes'?Number($('count').value):0};display(response);try{localStorage.setItem(KEY,JSON.stringify(response));}catch{$('result').textContent+=' Este navegador no permite guardar la respuesta.';}});$('guest').addEventListener('input',()=>$('guest').setCustomValidity(''));
try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved&&typeof saved.name==='string'&&['yes','no'].includes(saved.attendance))display(saved);}catch{}
$('reset').addEventListener('click',()=>{try{localStorage.removeItem(KEY);}catch{}$('result').hidden=true;$('reset').hidden=true;$('rsvpForm').reset();$('count').disabled=false;});
// Melodía sintetizada de ejemplo: no requiere un archivo ni reproduce sola.
let audioContext,musicTimer,musicOn=false;const notes=[261.63,329.63,392,523.25,440,392,329.63,293.66];
async function stopMusic(){musicOn=false;clearInterval(musicTimer);if(audioContext&&audioContext.state==='running')await audioContext.suspend();$('sound').textContent='♫ Música: apagada';$('sound').setAttribute('aria-pressed','false');}
$('sound').addEventListener('click',async()=>{try{if(musicOn){await stopMusic();return;}audioContext??=new (window.AudioContext||window.webkitAudioContext)();await audioContext.resume();musicOn=true;let n=0;const play=()=>{if(!musicOn)return;const oscillator=audioContext.createOscillator(),gain=audioContext.createGain(),now=audioContext.currentTime;oscillator.type='sine';oscillator.frequency.value=notes[n++%notes.length];gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(.08,now+.04);gain.gain.exponentialRampToValueAtTime(.001,now+1.4);oscillator.connect(gain);gain.connect(audioContext.destination);oscillator.start(now);oscillator.stop(now+1.5);};play();musicTimer=setInterval(play,600);$('sound').textContent='♫ Música: encendida';$('sound').setAttribute('aria-pressed','true');}catch{$('sound').textContent='Música no disponible';}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&musicOn)stopMusic();});
